medical_center/urls.py
# from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from User.views import index, login_view, register_view, doctors_view, edit_doctor_view, delete_doctor_view
from appointment.views import appointments_view, profile_view, complete_appointment_view, note_view


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('doctors/', doctors_view, name='doctors'),
    path('appointments/', appointments_view, name='appointments'),
    path('done/<int:appointment_id>', complete_appointment_view, name='done'),
    path('note/<int:appointment_id>', note_view, name='note'),
    path('about/', index, name='about'),
    path('login/', login_view, name='login'),
    path('signup/', register_view, name='signup'),
    path('edit/<int:doctor_id>', edit_doctor_view, name='edit'),
    path('delete/<int:doctor_id>', delete_doctor_view, name='delete'),
    path('profile/', profile_view, name='profile'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointment/models.py
from django.db import models
from User.models import User


class Appointment(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    doctor = models.ForeignKey(User, related_name='Doctor', on_delete=models.CASCADE)
    age = models.PositiveSmallIntegerField()
    gender = models.CharField(max_length=6)
    datetime = models.DateTimeField()
    is_done = models.BooleanField(default=False, null=True, blank=True)
    note = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

User/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth.forms import UserCreationForm
from .models import User


class RegistrationForm(UserCreationForm):
    name = forms.CharField(widget=widgets.TextInput(attrs={'class': 'text-field', 'placeholder': 'الاسم الكامل'}))
    email = forms.EmailField(widget=widgets.EmailInput(attrs={'class': 'text-field', 'placeholder': 'الايميل'}))
    password1 = forms.CharField(widget=widgets.PasswordInput(attrs={'class': 'text-field', 'placeholder': 'الرمز'}))
    password2 = forms.CharField(widget=widgets.PasswordInput(attrs={'class': 'text-field', 'placeholder': 'تأكيد الرمز'}))
    image = forms.ImageField(widget=widgets.FileInput(attrs={'class': 'file-field', 'accept': 'image/*'}), required=True)
    specialty = forms.CharField(widget=widgets.TextInput(attrs={'class': 'text-field', 'placeholder': 'التخصص'}), required=True)
    is_superuser = forms.BooleanField(widget=widgets.CheckboxInput(attrs={'class': 'check-field'}), required=False)
    is_doctor = forms.BooleanField(widget=widgets.CheckboxInput(attrs={'class': 'check-field'}), required=False)

    class Meta:
        model = User
        fields = ('name', 'email', 'password1', 'password2', 'image', 'specialty', 'is_superuser', 'is_doctor')
        error_messages = 'Error'


class LoginForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'text-field', 'placeholder': 'الايميل'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'text-field', 'placeholder': 'الرمز'}))

appointment/forms.py
from django import forms
from django.forms import widgets
from User.models import User
from .models import Appointment
from django.db import models


class AppointmentForm(forms.ModelForm):
    doctor = forms.ModelChoiceField(
        queryset=User.objects.filter(is_doctor=True).all(),
        empty_label='الطبيب المختص',
        widget=forms.Select(attrs={'class': 'choice-field'}),
        initial=None
    )

    class Meta:
        model = Appointment
        fields = ['name', 'phone', 'doctor', 'age', 'gender', 'datetime']
        widgets = {
            'name': widgets.TextInput(attrs={'class': 'text-field', 'placeholder': 'الاسم الثلاثي'}),
            'phone': widgets.TextInput(attrs={'class': 'text-field', 'placeholder': 'رقم الهاتف'}),
            'age': widgets.NumberInput(attrs={'class': 'num-field', 'placeholder': 'العمر'}),
            'gender': widgets.TextInput(attrs={'class': 'text-field', 'placeholder': 'الجنس'}),
            'datetime': widgets.DateTimeInput(attrs={'class': 'datetime-field', 'placeholder': 'موعد الحجز (تاريخاًُ ووقتاً)'})
        }


class CompleteAppointmentForm(forms.ModelForm):

    class Meta:
        model = Appointment
        fields = ['note']
        widgets = {
            'note': widgets.Textarea(attrs={'class': 'text-field', 'placeholder': 'الملاحظة'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['is_done'] = True

appointment/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from User.models import User
from .forms import AppointmentForm, CompleteAppointmentForm
from django.contrib.auth import get_user
from .models import Appointment


def appointments_view(request):
    if request.method == "POST":
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save()
        redirect('home')
    else:
        doctor_id = request.GET.get('doctor_id')
        if doctor_id:
            doctor = User.objects.get(id=doctor_id)
            form = AppointmentForm(initial={'doctor': doctor})
        else:
            form = AppointmentForm()
    return render(request, 'appointments.html', {'form': form})


def profile_view(request):
    user = get_user(request=request)
    is_done = request.GET.get('done')
    is_done = 0 if not is_done else is_done
    if user.is_superuser:
        appointments = Appointment.objects.filter(is_done=is_done).all()
    else:
        appointments = Appointment.objects.filter(doctor_id=user.id, is_done=is_done).all()
    is_done = True if is_done == '1' else False
    context = {
        'is_done': is_done,
        'appointments': appointments,
    }
    return render(request, 'profile.html', context)


def complete_appointment_view(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.method == 'POST':
        form = CompleteAppointmentForm(request.POST, instance=appointment)
        if form.is_valid():
            form.instance.is_done = True
            form.save()
            return redirect(reverse('profile')+'?done=0')
    else:
        form = CompleteAppointmentForm(instance=appointment)
    return render(request, 'complete_appointment.html', {'form': form})


def note_view(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    context = {
        'appointment': appointment
    }
    return render(request, 'note.html', context)

templates/appointments.html
{% extends 'index.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="appointment-page">
            <h3 style="color: #00BBFF">احجز موعداً</h3>
            <div class="col-div">
            <div class="row-div">
                {{form.doctor}}
                {{form.name}}
            </div>
            <div class="row-div">
                {{form.gender}}
                {{form.age}}
            </div>
            <div class="row-div">
                {{form.datetime}}
                {{form.phone}}
            </div>
        </div>
        <button class="button" type="submit"> حجز</button>
        </div>
    </form>
{% endblock %}
</body>
</html>

templates/complete_appointment.html
{% extends 'index.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <form method="post">
        <div class="complete-appointment">
            {% csrf_token %}
            {{ form.note }}
            <input type="hidden" name="is_done" value="True">
            <button class="button" type="submit">حفظ</button>
        </div>
    </form>
{% endblock %}
</body>
</html>

templates/doctors.html
{% extends 'index.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
        <div class="doctor-page">
        <h3 style="color: #00BBFF">الاطباء</h3>
        <ul class="doctor-page">
            {% for doctor in doctors %}
                <div style="display: flex; flex-direction: column; align-items: center">
                    <div>
                        <li class="doctor">
                            <img class="doc_img" src="/{{ doctor.image }}" alt="">
                            <h2>{{ doctor.name }}</h2>
                            <h3>{{ doctor.specialty }}</h3>
                            <a class="button" href="{% url 'appointments' %}?doctor_id={{ doctor.id }}">احجز موعداً</a>
                        </li>
                    </div>
                    <div class="edit-delete">
                        <a class="edit-delete-button" href="/edit/{{ doctor.id }}">تعديل</a>
                        <a class="edit-delete-button" href="/delete/{{ doctor.id }}">حذف</a>
                    </div>
                </div>
            {% endfor %}
        </ul>
        <button class="button" onclick="showMoreButton({{ length }})">عرض المزيد</button>
    </div>
    <script src={% static 'js/script.js' %}></script>
{% endblock %}
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Medical Center</title>
    <link rel="stylesheet" href={% static 'css/style.css' %}>
</head>
<body>
    <nav>
        <div class="container">
            <ul>
                <div>
                    {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                            <li><a class="button" href="{% url 'signup' %}">اضافة حساب</a></li>
                        {% endif %}
                    <li><a href="{% url 'profile' %}?done=0">حسابي</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">تسحيل دخول</a></li>
                    {% endif %}
                </div>
                <div>
                    <li><a href="{% url 'about' %}">حول</a></li>
                    <li><a href="{% url 'appointments' %}">المواعيد</a></li>
                    <li><a href="{% url 'doctors' %}?d=5">الاطباء</a></li>
                    <li><a href="{% url 'home' %}">الصفحة الرئيسية</a></li>
                </div>
            </ul>
        </div>
    </nav>
    {#<main>#}
    {% block content %}
        <div class="main_section">
            <div>
            <h1 class="hello_text">نحن نقدم استشارة عالية الجودة مع أفضل الأطباء لدينا</h1>
            <div>
            <a class="button" href="{% url 'about' %}">اقرء اكثر</a>
            <a class="button" href="{% url 'doctors' %}">بحث عن دكتور</a>
            </div>
            </div>
            <img src="../static/img/welcome.png" alt="" class="img">
        </div>
        <div class="suggested_section">
            <h3 style="color: white">الاطباء المقترحون</h3>
            <ul class="suggested_section div">
                {% for doctor in doctors %}
                    <li class="doctor">
                        <img class="doc_img" src="{{ doctor.image }}" alt="">
                        <h2>{{ doctor.name }}</h2>
                        <h3>{{ doctor.specialty }}</h3>
                        <a class="button" href="{% url 'appointments' %}?doctor_id={{ doctor.id }}">احجز موعداً</a>
                    </li>
                {% endfor %}
            </ul>
            <a class="button_inv" href="{% url 'doctors' %}">عرض المزيد</a>
        </div>
        <div class="about_section">
            <h3>عنا</h3>
            <div class="about_section div">
                <img class="group_doc_img" src="../static/img/group%20doctor.png" alt="">
                <h2>نعتقد أن الرعاية الصحية هي أكثر من مجرد علاج الأعراض ؛ يتعلق الأمر بمعالجة الأسباب الكامنة وراء المرض وتعزيز العافية بشكل عام. لهذا السبب نقدم مجموعة من الخدمات ، بما في ذلك الرعاية الوقائية والاختبارات التشخيصية والعلاجات والإجراءات المتقدمة.</h2>
            </div>
        </div>
    {% endblock %}
    <footer class="footer">
        <h1>العراق, بابل<br> الحلة, شارع 40</h1>
        <div class="footer-info">
            <div class="footer-social">
              <img src="../static/img/facebook.png" alt="facebook">
              <img src="../static/img/instagram.png" alt="instagram">
              <img src="../static/img/telegram.png" alt="telegram">
              <img src="../static/img/twitter.png" alt="twitter">
            </div>
        </div>
        <div class="footer-info">
            <h2>تواصل معنا</h2>
            <p>example@mail.com</p>
            <p>07801234567</p>
        </div>
    </footer>
    {#    <p>Here you can find all the information you need about our services.</p>#}
{#</main>#}
</body>
</html>

templates/login.html
{% extends 'index.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<form method="post">
{% csrf_token %}
    <div class="login-page">
        <img src="{% static 'img/login.png' %}" alt="">
        <div class="login-page div">
            <h1>تسجيل دخول</h1>
            {{ form.email }}
            {{ form.password }}
            <button class="button" type="submit"> login</button>
        </div>
    </div>
</form>
{% endblock %}
</body>
</html>

templates/note.html
{% extends 'index.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <div class="note">
        <div>
            <h3><span>الاسم:  </span>{{ appointment.name }}</h3>
        </div>
        <div>
            <h3><span>رقم الهاتف:  </span>{{ appointment.phone }}</h3>
        </div>
        <div>
            <h3><span>الطبيب المختص:  </span>{{ appointment.doctor }}</h3>
        </div>
        <div>
            <h3><span>العمر:  </span>{{ appointment.age }}</h3>
        </div>
        <div>
            <h3><span>الجنس:  </span>{{ appointment.gender }}</h3>
        </div>
        <div>
            <h3>{{ appointment.datetime }}<span>  :تاريخ الحجز</span></h3>
        </div>
        <div>
            <h3><span>الملاحضات:  </span>{{ appointment.note }}</h3>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/profile.html
{% extends 'index.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <div style="min-height: 35vmax">
    <div class="my-appointment-buttons">
        <button class="my-appointment-buttons button" onclick="getDoneAppointmentsButton()">المواعيد المنجزة</button>
        <button class="my-appointment-buttons button" onclick="getUndoneAppointmentsButton()">المواعيد غير المنجزة</button>
    </div>
    <table class="my-appointments-page">
            <tr class="app-item">
                {% if not is_done %}
                    <th>تحديد كتامة</th>
                {% else %}
                    <th>الملاحظات</th>
                {% endif %}
                <th>الموعد</th>
                <th>رقم الهاتف</th>
                <th>العمر</th>
                <th>الجنس</th>
                <th>الاسم</th>
            </tr>
        {% for appointment in appointments %}
            <tr>
                {% if not is_done %}
                    <td><a class="my-appointments-page a" href={% url 'done' appointment.id%}>اتمام</a></td>
                {% else %}
                    <td><a class="my-appointments-page a" href="{% url 'note' appointment.id%}">عرض</a></td>
                {% endif %}
                <td>{{ appointment.datetime }}</td>
                <td>{{ appointment.phone }}</td>
                <td>{{ appointment.age }}</td>
                <td>{{ appointment.gender }}</td>
                <td>{{ appointment }}</td>
            </tr>
        {% endfor %}
        </table>
    </div>
    <script src={% static 'js/script.js' %}></script>
{% endblock %}
</body>
</html>

templates/register.html
{% extends 'index.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div style="display:flex; flex-direction: row-reverse">
            <div class="register-page">
            {{ form.name }}
            {{ form.specialty }}
            {{ form.email }}
            {{ form.password1 }}
            {{ form.password2 }}
            <div>
                <div>
                    {{ form.is_superuser }}
                    <label for="id_is_superuser">ادمن</label>
                </div>
                <div>
                    {{ form.is_doctor }}
                    <label for="id_is_doctor">طبيب</label>
                </div>
            </div>
            <div>
                <label for="id_image">اختر صوره</label>
                {{ form.image }}
            </div>
        <button class="button" type="submit">حفظ</button>
        </div>
            <img src="/static/img/sign%20up.png" alt="" style="width: 40%;height: 40%">
        </div>
    </form>
{% endblock %}
</body>
</html>